# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: '#about'
    weight: 10
  # - name: Experience
  #   url: '#experience'
  #   weight: 20
  - name: Technical
    url: '#technical'
    weight: 30
  - name: Languages
    url: '#languages'
    weight: 40
  - name: 
    url: ''
    weight: 50
  - name: Coursework
    url: '/coursework'
    weight: 60
  - name: Teaching
    url: '/teaching'
    weight: 70
  # - name: Research
  #   url: '/publications'
  #   weight: 80
  # - name: Contact
  #   url: '#contact'
  #   weight: 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
  # - name: CV
  #   url: /uploads/AraPatvakanianResume.pdf
  #   weight: 80
