# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  theme_day: aptheme # "minimal" = Default
  theme_night: aptheme # "minimal" = Default
  font: minimal
  font_size: M

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'The Personal Website of Ara Patvakanian'
    twitter: 'AraPatvakanian'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''  
  verification:
    google: 'xoybPssYr1WW5yah6HQOwU3hvNjiFJdtD93WjfzvSCk'
    baidu: ''

# Site Header
header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: false # Change to true for search bar
    highlight_active_link: true

# Site Footer
footer:
  copyright:
    notice: '© 2023–Present Ara Patvakanian | Website License {license}' # {year}
    license:
      enable: true
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

# Localization
# https://gohugo.io/functions/time/format/
locale:
  date_format: '2006.01.02' # 'January 2, 2006' 
  time_format: '3:04 PM'
  address_format: en-us

  timezone: 'America/Los_Angeles'  # Recommended: Handles DST automatically
  offset: '-08:00'

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: '' # Change to "wowchemy" (no quotes) to enable; change to '' to disable
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: false
